### ISSUE TITLE
DO NOT DOWNLOAD THIS IT WILL STEAL DISCORD TOKENS, MINECRAFT ACCOUNTS, AND COOKIES

### ISSUE THREAD

**Issue by SpicyTakis** [auraflipper/Aura-flipper#1]

**Comment by DarthGigi** [comment]
https://isthisarat.com/score/84178f5287c6fae2f22b82312016c94091aef27cc10c5d1c0cf2ac7a81d458ec

**Comment by brecht2202** [comment]
This guy is spreading a RAT malware focused at kids. 
He made some previous videos and github account under the name "cashcow32" which he now privated/deleted which were prettty much the same thing. (This is his new scam spreading video to advertise the malware infested mod: https://www.youtube.com/watch?v=i4f5adxTBD4)
The minecraft mod he made will get all login info from any account on the victim's pc. (Discord, Mail, Bank info, ...)

**Comment by brecht2202** [comment]
Everyone who comes across this, please report the account.

**Comment by DarthGigi** [comment]
Reported

**Comment by brecht2202** [comment]
He deleted this thread lmao
