### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by playfuldoggo** [auraflipper/Aura-flipper#99]
maybe deobfuscate your shady code covered in crumb trails from this "better chat" mod and ill consider using your rat ;)

**Comment by DarthGigi** [comment]
💀

**Comment by brecht2202** [comment]
lmao

**Comment by squarecubelaw** [comment]
bro idk how this could be more obvious 💀

**Comment by brecht2202** [comment]
don't forget to report his acc

**Comment by playfuldoggo** [comment]
i downloaded it on a vm and checked the code and is is the shadiest shit ever

**Comment by brecht2202** [comment]
cashcow32 has been redoing this the past month over and over

**Comment by playfuldoggo** [comment]
let alone the shadiness that not having the code on github is

**Comment by brecht2202** [comment]
ofcourse he closed this

**Comment by DarthGigi** [comment]
> i downloaded it on a vm and checked the code and is is the shadiest shit ever

Just use https://isthisarat.com/
Here is the result for this file: https://isthisarat.com/score/84178f5287c6fae2f22b82312016c94091aef27cc10c5d1c0cf2ac7a81d458ec
